---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cs-opensourceways-com-v1alpha1-codeserver
  failurePolicy: Fail
  name: mcodeserver.kb.io
  rules:
  - apiGroups:
    - cs.opensourceways.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - codeservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cs-opensourceways-com-v1alpha1-codeserver
  failurePolicy: Fail
  name: vcodeserver.kb.io
  rules:
  - apiGroups:
    - cs.opensourceways.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - codeservers
  sideEffects: None
