---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserver
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserver/finalizers
  verbs:
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserver/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserverdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserverdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserverdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeservers/finalizers
  verbs:
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
