---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cs.opensourceways.com
  resources:
  - codeservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.opensourceways.com
  resources:
  - codeservers/finalizers
  verbs:
  - update
- apiGroups:
  - cs.opensourceways.com
  resources:
  - codeservers/status
  verbs:
  - get
  - patch
  - update
