apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: codeserver-access
spec:
  podSelector:
    matchLabels:
      app: codeserver
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app: control-ingress
