apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "code-server-operator.fullname" . }}-manager-role
  labels:
  {{- include "code-server-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserver
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserver/finalizers
  verbs:
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserver/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserverdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserverdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeserverdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeservers/finalizers
  verbs:
  - update
- apiGroups:
  - cs.walnuts.dev
  resources:
  - codeservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "code-server-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: code-server-operator
    app.kubernetes.io/part-of: code-server-operator
  {{- include "code-server-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "code-server-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "code-server-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'