apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "code-server-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: code-server-operator
    app.kubernetes.io/part-of: code-server-operator
  {{- include "code-server-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}